import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import SideBar from "@/components/SideBar";
import StateProvider from "@/context/StateContext";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const sans = DM_Sans({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: "--font-DM-Sans",

})


export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "ITechno Portofolio || pages",
    template: "ITechno Portofolio || %s"
  },
  description: "Generated by create next app",
  icons: {
    icon: ['/logo2.png?v=4']
  }
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StateProvider>
        <body className={`${sans.variable}`}>
          <SideBar />
          <NavBar />
          {children}
          <Footer />
        </body>
      </StateProvider>
    </html>
  );
}
